version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: library_system
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_pass
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    depends_on:
      - mysql

volumes:
  mysql-data:
